acme_nfl.settings:
  type: config_object
  label: 'ACME NFL Settings'
  mapping:
    langcode:
      type: string
      label: 'Language code'
    nfl_teams_api_endpoint:
      type: string
      label: 'NFL Teams API Endpoint'
